schema:
  format:
    openapi: "3.0.0"
  service_input_type: "LoadBalancedFargateServiceInput"
  pipeline_input_type: "PipelineInputs"

  types:
    LoadBalancedFargateServiceInput:
      type: object
      description: "Input properties for a loadbalanced Fargate service"
      properties:
        port:
          title: "Port"
          type: number
          default: 443
          minimum: 0
          maximum: 65535
        desired_count:
          title: "Desired count"
          type: number
          default: 1
          minimum: 1
        task_size:
          title: "Task size"
          type: string
          enum: ["x-small", "small", "medium", "large", "x-large"]
          default: "medium"
        subnet_type:
          title: "Subnet Type"
          type: string
          enum: ["public", "private"]
          default: "public"
        loadbalancer_type:
          title: "Load Balancer Type"
          type: string
          enum: ["application", "network"]
          default: "network"
        image:
          title: "Image"
          type: string
          default: "mcr.microsoft.com/dotnet/sdk:6.0"
          minLength: 1
          maxLength: 200
        backendurl:
          title: "Backend URL"
          type: string
          default: "companyx.com"
          minLength: 1
          maxLength: 200

    PipelineInputs:
      type: object
      description: "Pipeline input properties"
      properties:
        service_dir:
          title: "Application Code Directory"
          type: string
          default: "ecs-static-website"
          minLength: 1
          maxLength: 100
        dockerfile:
          title: "Dockerfile"
          type: string
          default: "Dockerfile"
          minLength: 1
          maxLength: 100
        unit_test_command:
          title: "Unit test command"
          type: string
          default: "echo 'add your unit test command here'"
          minLength: 1
          maxLength: 200